### ISSUE TITLE
I must be autistic or smtn

### ISSUE THREAD

**Issue by RuneGaming** [Crystallinqq2/qqAntiVirus#3]
I must be autistic or smtn, but when I run the prebuilt jar nothing happens just does nothing.

**Comment by y4ndex1** [comment]
> I must be autistic or smtn, but when I run the prebuilt jar nothing happens just does nothing.

you do have autism. https://www.reddit.com/r/minecraftclients/comments/l2zmfn/emergency_check_this_file_path_right_now/ just check this reddit post lol

**Comment by RuneGaming** [comment]
ez

**Comment by Crystallinqq2** [comment]
java -jar qqAntiVirus-1.0-SNAPSHOT.jar in command prompt

**Comment by Crystallinqq2** [comment]
> > I must be autistic or smtn, but when I run the prebuilt jar nothing happens just does nothing.
> 
> you do have autism. https://www.reddit.com/r/minecraftclients/comments/l2zmfn/emergency_check_this_file_path_right_now/ just check this reddit post lol

Arent u the guy who threatened to kill himself because he didnt get a pyro key? Weird fuck.

**Comment by YeahOMA** [comment]
Heya Crystalinqq thanks for making this! I'm the dude who posted the Reddit post- 

https://www.reddit.com/r/minecraftclients/comments/l2zmfn/emergency_check_this_file_path_right_now/

**Comment by Crystallinqq2** [comment]
@YeahOMA meme thread. i found this malware weeks ago but u guys were not saying anything back then lmao.

**Comment by RuneGaming** [comment]
never bought or used pyro
